### ISSUE TITLE
Update the database and the routes descriptions (2 hours) f-1, f-2, nf-3

### ISSUE THREAD

**Issue by Aardes-Roiven** [Suwi-inc/LBS-server#31]
The db and the routes have updates, but the SRS doesn't contain this information. The task is to update the information in the doc according to the actual situationUpdate the database description. There are new attributes

**Comment by ParfenovIgor** [comment]
https://docs.google.com/document/d/1Ug4wAN2sqtkQ-wAW9JKwNl4G9Y3X2b_IAK59tggbiGw

**Comment by Aardes-Roiven** [comment]
@Suwi-inc, please verify the changes and ensure that they reflect reality before applying them

**Comment by Suwi-inc** [comment]
src updated
