### ISSUE TITLE
Add linters to CI

### ISSUE THREAD

**Issue by ParfenovIgor** [Suwi-inc/LBS-server#50]
Add `ruff`, `yamlfix` and `hadolint` linters to CI.
Currently most of the files fail this check.

**Comment by Aardes-Roiven** [comment]
don't forget to add estimations

**Comment by ParfenovIgor** [comment]
I think, the time for adding this is negligible small in comparison with the time for fixing merge conflicts.

**Comment by ParfenovIgor** [comment]
How are we supposed to install `hadolint`? Installing it locally looks weird.
